In Runtime, select Change Runtime type to enable GPU.

Your first PyTorch code;

In [25]:
import torch
print("CUDA availability:")
print(torch.cuda.is_available())
print("New tensor:")
print(torch.rand(2,2))

CUDA availability:
True
New tensor
tensor([[0.4835, 0.3727],
        [0.7937, 0.4305]])


Tensor initial code


In [26]:
import torch
print("New tensor:")
x = torch.tensor([[0, 0, 1], [1, 1, 1], [0, 0, 0]])
print(x)

print("Single value operation:")
x[0][0] = 5
print(x)

print("Zero tensor:")
x = torch.zeros(2, 2)
print(x)

print("Tensor Sum:")
x = torch.ones(1, 2) + torch.ones(1, 2)
print(x)

# use item to get 1d value
print("Get 1d value:")
x= torch.rand(1).item()
print(x)

# check tensor storage memory type
print("Check tensor storage memory type")
cpu_tensor = torch.rand(2)
print(cpu_tensor.device)
gpu_tensor = cpu_tensor.to("cuda")
print(gpu_tensor.device)

New tensor:
tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])
Single value operation:
tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])
Zero tensor:
tensor([[0., 0.],
        [0., 0.]])
Tensor Sum:
tensor([[2., 2.]])
Get 1d value:
0.9706895351409912
check tensor storage memory type
cpu
cuda:0


Basic Tensor Operations

In [30]:
import torch
print("Max:")
x = torch.rand(2, 2).max()
print(x)
print(x.item())

# data type
print("Check data type:")
long_tensor = torch.tensor([[0, 0, 1], [1, 1, 1], [0, 0, 0]])
print(long_tensor.type())
float_tensor = long_tensor.to(dtype=torch.float32)
print(float_tensor.type())

# in-place function (ends with an "_") will save the tensor in place after operation
print("Check in-place function:")
x = torch.rand(2, 2)
# check the type to get the object address and see if they are the same
print(x.type)
print(x.log2().type)
print(x.log2_().type)

# reshape
print("Reshape and view:")
x = torch.rand(784)
y = x.view(1, 28, 28)
print(y.shape)
# search for the difference between view() and reshape() if interested
z = x.reshape(1, 28, 28)
print(z.shape)

# permuation
print("Permutation:")
x = torch.rand(640, 480, 3)
y = x.permute(2, 0, 1)
print(y.shape)

# broadcasting
print("Broadcasting:")
x = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
y = torch.tensor([1, 2, 3])
z = x + y
print(z)

Max:
tensor(0.8663)
0.8662620186805725
Check data type:
torch.LongTensor
torch.FloatTensor
Check in-place function:
<built-in method type of Tensor object at 0x7f4a056c3550>
<built-in method type of Tensor object at 0x7f4a056c35a0>
<built-in method type of Tensor object at 0x7f4a056c3550>
Reshape and view:
torch.Size([1, 28, 28])
torch.Size([1, 28, 28])
Permutation:
torch.Size([3, 640, 480])
Broadcasting:
tensor([[2, 2, 3],
        [1, 3, 3],
        [1, 2, 4]])
